export const data = [
  {
    num: '1',
    name: 'large ball with paint',
    amount: '2',
    year: '1960',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '2',
    name: 'green ball with flowers',
    amount: '5',
    year: '2000',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '3',
    name: 'red mate ball',
    amount: '3',
    year: '1990',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '4',
    name: 'icicle red',
    amount: '2',
    year: '1980',
    form: 'toy',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '5',
    name: 'red grape',
    amount: '4',
    year: '1980',
    form: 'toy',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '6',
    name: 'red ball with picture',
    amount: '6',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '7',
    name: 'Milk-white ball',
    amount: '12',
    year: '1960',
    form: 'ball',
    color: 'white',
    size: 'medium',
    favorite: true,
  },
  {
    num: '8',
    name: 'red ball',
    amount: '10',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '9',
    name: 'bell vintage',
    amount: '2',
    year: '1950',
    form: 'bell',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '10',
    name: 'white ball vintage',
    amount: '7',
    year: '1960',
    form: 'ball',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '11',
    name: 'cone tree white',
    amount: '11',
    year: '1960',
    form: 'cone',
    color: 'white',
    size: 'small',
    favorite: false,
  },
  {
    num: '12',
    name: 'white ball with flowers',
    amount: '5',
    year: '1980',
    form: 'ball',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '13',
    name: 'ball river picture',
    amount: '3',
    year: '1970',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: true,
  },
  {
    num: '14',
    name: 'ball village picture',
    amount: '4',
    year: '1970',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: true,
  },
  {
    num: '15',
    name: 'bell pictured',
    amount: '3',
    year: '1970',
    form: 'bell',
    color: 'blue',
    size: 'medium',
    favorite: false,
  },
  {
    num: '16',
    name: 'cone nature picture',
    amount: '3',
    year: '1970',
    form: 'cone',
    color: 'blue',
    size: 'medium',
    favorite: true,
  },
  {
    num: '17',
    name: 'cone pictured',
    amount: '7',
    year: '1970',
    form: 'cone',
    color: 'red',
    size: 'medium',
    favorite: false,
  },
  {
    num: '18',
    name: 'yellow ball with knot',
    amount: '2',
    year: '2010',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '19',
    name: 'yellow ball with something',
    amount: '12',
    year: '1980',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '20',
    name: 'red ball with knot',
    amount: '8',
    year: '1950',
    form: 'ball',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '21',
    name: 'red ball with stars',
    amount: '4',
    year: '1970',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: true,
  },
  {
    num: '22',
    name: 'cone golden tree',
    amount: '11',
    year: '1990',
    form: 'cone',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '23',
    name: 'bell vintage',
    amount: '9',
    year: '1950',
    form: 'bell',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '24',
    name: 'star graceful',
    amount: '1',
    year: '1940',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '25',
    name: 'Pink ball with confetti',
    amount: '12',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '26',
    name: 'Ruby-golden ball',
    amount: '8',
    year: '1960',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '27',
    name: 'red ball with paint',
    amount: '4',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '28',
    name: 'Burgundy ball with paint',
    amount: '10',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '29',
    name: 'Retro ball with flowers',
    amount: '5',
    year: '1950',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: true,
  },
  {
    num: '30',
    name: 'Retro ball with paint',
    amount: '8',
    year: '1950',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: true,
  },
  {
    num: '31',
    name: 'red ball with confetti',
    amount: '8',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '32',
    name: 'blue ball Galaxy',
    amount: '11',
    year: '1970',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: false,
  },
  {
    num: '33',
    name: 'blue ball with snowflake',
    amount: '6',
    year: '2010',
    form: 'ball',
    color: 'blue',
    size: 'medium',
    favorite: false,
  },
  {
    num: '34',
    name: 'green  ball with picture',
    amount: '8',
    year: '2010',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '35',
    name: 'toy fox in ball',
    amount: '8',
    year: '1950',
    form: 'toy',
    color: 'yellow',
    size: 'medium',
    favorite: true,
  },
  {
    num: '36',
    name: 'Purple ball blizzard',
    amount: '1',
    year: '2000',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: false,
  },
  {
    num: '37',
    name: 'green  ball blizzard',
    amount: '6',
    year: '2000',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '38',
    name: 'Blue  ball blizzard',
    amount: '6',
    year: '2000',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: false,
  },
  {
    num: '39',
    name: 'red star',
    amount: '6',
    year: '1990',
    form: 'star',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '40',
    name: 'star golden',
    amount: '12',
    year: '2020',
    form: 'star',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '41',
    name: 'star arctic',
    amount: '11',
    year: '2020',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '42',
    name: 'green ball',
    amount: '10',
    year: '1980',
    form: 'ball',
    color: 'green',
    size: 'medium',
    favorite: false,
  },
  {
    num: '43',
    name: 'star two colored',
    amount: '6',
    year: '1960',
    form: 'star',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '44',
    name: 'toy angel',
    amount: '11',
    year: '1940',
    form: 'toy',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '45',
    name: 'star christmas',
    amount: '1',
    year: '1980',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '46',
    name: 'toy amanita',
    amount: '10',
    year: '1950',
    form: 'toy',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '47',
    name: 'toy well',
    amount: '6',
    year: '1950',
    form: 'toy',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '48',
    name: 'yellow ball with tie',
    amount: '6',
    year: '1960',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '49',
    name: 'star with something',
    amount: '4',
    year: '1980',
    form: 'star',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '50',
    name: 'bell large',
    amount: '3',
    year: '2020',
    form: 'bell',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '51',
    name: 'cone with blizzard',
    amount: '12',
    year: '1970',
    form: 'cone',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '52',
    name: 'red ball with writing',
    amount: '12',
    year: '1990',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: true,
  },
  {
    num: '53',
    name: 'star silver',
    amount: '6',
    year: '2020',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '54',
    name: 'green ball with picture',
    amount: '6',
    year: '2010',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '55',
    name: 'ginger house',
    amount: '1',
    year: '1940',
    form: 'toy',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '56',
    name: 'ginger castle',
    amount: '1',
    year: '1940',
    form: 'toy',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '57',
    name: 'ginger hut',
    amount: '1',
    year: '1940',
    form: 'toy',
    color: 'yellow',
    size: 'medium',
    favorite: false,
  },
  {
    num: '58',
    name: 'toy white bear',
    amount: '2',
    year: '1980',
    form: 'toy',
    color: 'white',
    size: 'medium',
    favorite: false,
  },
  {
    num: '59',
    name: 'yellow ball with writing',
    amount: '10',
    year: '1990',
    form: 'ball',
    color: 'yellow',
    size: 'medium',
    favorite: false,
  },
  {
    num: '60',
    name: 'toy pigeon',
    amount: '12',
    year: '1940',
    form: 'toy',
    color: 'white',
    size: 'medium',
    favorite: true,
  },
];

export default data;
