const data = [
  {
    num: '1',
    name: 'large ball with paint',
    count: '2',
    year: '1960',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '2',
    name: 'green ball with flowers',
    count: '5',
    year: '2000',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '3',
    name: 'red mate ball',
    count: '3',
    year: '1990',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '4',
    name: 'Сосулька красная',
    count: '2',
    year: '1980',
    form: 'toy',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '5',
    name: 'red виноград',
    count: '4',
    year: '1980',
    form: 'toy',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '6',
    name: 'red ball с рисунком',
    count: '6',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '7',
    name: 'Молочно-white ball',
    count: '12',
    year: '1960',
    form: 'ball',
    color: 'white',
    size: 'medium',
    favorite: true,
  },
  {
    num: '8',
    name: 'red ball',
    count: '10',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '9',
    name: 'bell старинный',
    count: '2',
    year: '1950',
    form: 'bell',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '10',
    name: 'white ball ретро',
    count: '7',
    year: '1960',
    form: 'ball',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '11',
    name: 'cone еловая белая',
    count: '11',
    year: '1960',
    form: 'cone',
    color: 'white',
    size: 'small',
    favorite: false,
  },
  {
    num: '12',
    name: 'white ball с цветами',
    count: '5',
    year: '1980',
    form: 'ball',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '13',
    name: 'ball расписной Река',
    count: '3',
    year: '1970',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: true,
  },
  {
    num: '14',
    name: 'ball расписной Деревня',
    count: '4',
    year: '1970',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: true,
  },
  {
    num: '15',
    name: 'bell расписной',
    count: '3',
    year: '1970',
    form: 'bell',
    color: 'blue',
    size: 'medium',
    favorite: false,
  },
  {
    num: '16',
    name: 'cone расписная Пейзаж',
    count: '3',
    year: '1970',
    form: 'cone',
    color: 'blue',
    size: 'medium',
    favorite: true,
  },
  {
    num: '17',
    name: 'cone расписная',
    count: '7',
    year: '1970',
    form: 'cone',
    color: 'red',
    size: 'medium',
    favorite: false,
  },
  {
    num: '18',
    name: 'yellow ball с бантом',
    count: '2',
    year: '2010',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '19',
    name: 'yellow ball с паетками',
    count: '12',
    year: '1980',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '20',
    name: 'red ball с бантом',
    count: '8',
    year: '1950',
    form: 'ball',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '21',
    name: 'red ball с звёздами',
    count: '4',
    year: '1970',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: true,
  },
  {
    num: '22',
    name: 'cone еловая золотая',
    count: '11',
    year: '1990',
    form: 'cone',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '23',
    name: 'bell старинный',
    count: '9',
    year: '1950',
    form: 'bell',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '24',
    name: 'star изящная',
    count: '1',
    year: '1940',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '25',
    name: 'Розовый ball с блёстками',
    count: '12',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '26',
    name: 'Рубиново-золотой ball',
    count: '8',
    year: '1960',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '27',
    name: 'red ball с узором',
    count: '4',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '28',
    name: 'Бордовый ball с узором',
    count: '10',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '29',
    name: 'Старинный ball с цветами',
    count: '5',
    year: '1950',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: true,
  },
  {
    num: '30',
    name: 'Старинный ball с узором',
    count: '8',
    year: '1950',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: true,
  },
  {
    num: '31',
    name: 'red ball с блёстками',
    count: '8',
    year: '2010',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '32',
    name: 'blue ball Вселенная',
    count: '11',
    year: '1970',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: false,
  },
  {
    num: '33',
    name: 'blue ball со снежинкой',
    count: '6',
    year: '2010',
    form: 'ball',
    color: 'blue',
    size: 'medium',
    favorite: false,
  },
  {
    num: '34',
    name: 'green  ball с узором',
    count: '8',
    year: '2010',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '35',
    name: 'toy Лис в ballфе',
    count: '8',
    year: '1950',
    form: 'toy',
    color: 'yellow',
    size: 'medium',
    favorite: true,
  },
  {
    num: '36',
    name: 'Сиреневый ball Метель',
    count: '1',
    year: '2000',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: false,
  },
  {
    num: '37',
    name: 'green  ball Метель',
    count: '6',
    year: '2000',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '38',
    name: 'Голубой  ball Метель',
    count: '6',
    year: '2000',
    form: 'ball',
    color: 'blue',
    size: 'large',
    favorite: false,
  },
  {
    num: '39',
    name: 'Красная star',
    count: '6',
    year: '1990',
    form: 'star',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '40',
    name: 'star золотая',
    count: '12',
    year: '2020',
    form: 'star',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '41',
    name: 'star арктическая',
    count: '11',
    year: '2020',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '42',
    name: 'green ball',
    count: '10',
    year: '1980',
    form: 'ball',
    color: 'green',
    size: 'medium',
    favorite: false,
  },
  {
    num: '43',
    name: 'star двухцветная',
    count: '6',
    year: '1960',
    form: 'star',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '44',
    name: 'toy Ангела',
    count: '11',
    year: '1940',
    form: 'toy',
    color: 'red',
    size: 'medium',
    favorite: true,
  },
  {
    num: '45',
    name: 'star новогодняя',
    count: '1',
    year: '1980',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '46',
    name: 'toy Мухомор',
    count: '10',
    year: '1950',
    form: 'toy',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '47',
    name: 'toy Колодец',
    count: '6',
    year: '1950',
    form: 'toy',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '48',
    name: 'yellow ball с бантом',
    count: '6',
    year: '1960',
    form: 'ball',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '49',
    name: 'star с бирюзой',
    count: '4',
    year: '1980',
    form: 'star',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '50',
    name: 'bell large',
    count: '3',
    year: '2020',
    form: 'bell',
    color: 'red',
    size: 'large',
    favorite: false,
  },
  {
    num: '51',
    name: 'cone с изморозью',
    count: '12',
    year: '1970',
    form: 'cone',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '52',
    name: 'red ball с надписью',
    count: '12',
    year: '1990',
    form: 'ball',
    color: 'red',
    size: 'large',
    favorite: true,
  },
  {
    num: '53',
    name: 'star серебристая',
    count: '6',
    year: '2020',
    form: 'star',
    color: 'white',
    size: 'large',
    favorite: false,
  },
  {
    num: '54',
    name: 'green ball с рисунком',
    count: '6',
    year: '2010',
    form: 'ball',
    color: 'green',
    size: 'large',
    favorite: false,
  },
  {
    num: '55',
    name: 'Пряничный домик',
    count: '1',
    year: '1940',
    form: 'toy',
    color: 'yellow',
    size: 'large',
    favorite: false,
  },
  {
    num: '56',
    name: 'Пряничный теремок',
    count: '1',
    year: '1940',
    form: 'toy',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '57',
    name: 'Пряничная избушка',
    count: '1',
    year: '1940',
    form: 'toy',
    color: 'yellow',
    size: 'medium',
    favorite: false,
  },
  {
    num: '58',
    name: 'toy белого медведя',
    count: '2',
    year: '1980',
    form: 'toy',
    color: 'white',
    size: 'medium',
    favorite: false,
  },
  {
    num: '59',
    name: 'yellow ball с надписью',
    count: '10',
    year: '1990',
    form: 'ball',
    color: 'yellow',
    size: 'medium',
    favorite: false,
  },
  {
    num: '60',
    name: 'toy Голубь',
    count: '12',
    year: '1940',
    form: 'toy',
    color: 'white',
    size: 'medium',
    favorite: true,
  },
];

export default data;
